Repository nbcamp-final-team3/stamp-it, pull requests merged in 2025-07, with the labels that each got.

#87 [Feat] STAMPIT-167 스탬프 모달 상세뷰 UI 구현
  StampIt-Project/StampIt-Project/Presentation/Home/Common/TagView.swift
  StampIt-Project/StampIt-Project/Presentation/Home/View/Subviews/MissionCardCell.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/View/StampBoard/StampBoardCollectionView.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/View/StampBoard/StampBoardTab.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/ViewController/StampBoardViewController.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/ViewController/StampInfoViewController.swift
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/Red/red300.colorset/Contents.json
Labels: 📱 UI/UX, 🎯 UIKit, 🦁 하경

#92 [Doc] STAMPIT-180 멤버 관리 데이터 정리 시나리오 문서화
  StampIt-Project/StampIt-Project/App/DIContainer.swift
  StampIt-Project/StampIt-Project/Data/RepositoryImpl/InviteRepositoryImpl.swift
  StampIt-Project/StampIt-Project/Domain/Repository/InviteRepository.swift
  StampIt-Project/StampIt-Project/Domain/UseCase/InviteUseCase.swift
  StampIt-Project/StampIt-Project/Domain/UseCaseImpl/InviteUseCaseImpl.swift
  StampIt-Project/StampIt-Project/Presentation/Invite/ViewController/ReceiveInviteViewController.swift
  StampIt-Project/StampIt-Project/Presentation/Invite/ViewModel/ReceiveInviteViewModel.swift
Labels: ✨ Feature, 📄 Docs, 🐯 주형

#104 [Hotfix] STAMPIT-192 - 그룹탈퇴 시 토스트 안 보이는 문제 해결 (빈배열 무한 대기 처리 로직 추가)
  StampIt-Project/StampIt-Project/Data/DataSources/Manager/Mission/MissionManager.swift
  StampIt-Project/StampIt-Project/Data/DataSources/Manager/Sticker/StickerManager.swift
Labels: 🧹 Refactor, 🦊 부용, 🐛 Bug

#105 [Fix] STAMPIT-196 - 커스텀 미션 제목 작성할 때 키보드 내려가지 않는 현상 해결
  StampIt-Project/StampIt-Project/Presentation/Mission/View/AssignMissionViewController.swift
Labels: 📱 UI/UX, 🐛 Bug, 🎯 UIKit, 🐻 순욱

#103 [Refactor] STAMPIT-195 미션 즐겨찾기 디자인 변경
  StampIt-Project/StampIt-Project/Presentation/Mission/View/MissionListViewController.swift
  StampIt-Project/StampIt-Project/Presentation/Mission/View/Subview/MissionListCell.swift
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/Mission/bookmarkGray.imageset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/Mission/bookmarkGray.imageset/bookmarkGray.svg
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/Mission/bookmarkRed.imageset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/Mission/bookmarkRed.imageset/bookmarkRed.svg
Labels: 🧹 Refactor, 📱 UI/UX, 🎯 UIKit, 🐻 순욱

#109 [Feat] STAMPIT-184 내 미션 더보기에서 미션 완료 취소하는 로직 수정
  StampIt-Project/StampIt-Project/Data/DataSources/Manager/Sticker/StickerManager.swift
  StampIt-Project/StampIt-Project/Data/DataSources/Manager/Sticker/StickerProtocol.swift
  StampIt-Project/StampIt-Project/Data/Entities/Query/StickerQuery.swift
  StampIt-Project/StampIt-Project/Data/RepositoryImpl/HomeRepositoryImpl.swift
  StampIt-Project/StampIt-Project/Domain/Entities/Mission.swift
  StampIt-Project/StampIt-Project/Domain/Repository/HomeRepository.swift
  StampIt-Project/StampIt-Project/Domain/UseCase/MyMissionUseCase.swift
  StampIt-Project/StampIt-Project/Domain/UseCaseImpl/MyMissionUseCaseImpl.swift
  StampIt-Project/StampIt-Project/Presentation/Common/Mapper/MissionMapper.swift
  StampIt-Project/StampIt-Project/Presentation/Home/Common/AssignedMissionCell.swift
  StampIt-Project/StampIt-Project/Presentation/Home/Common/MissionStateButton.swift
  StampIt-Project/StampIt-Project/Presentation/Home/Model/HomeItem.swift
  StampIt-Project/StampIt-Project/Presentation/Home/MyMission/View/MyMissionView.swift
  StampIt-Project/StampIt-Project/Presentation/Home/MyMission/ViewController/MyMissionViewController.swift
  StampIt-Project/StampIt-Project/Presentation/Home/MyMission/ViewModel/MyMissionViewModel.swift
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/Mission/checkRed200.imageset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/Mission/checkRed200.imageset/checkRed200.svg
Labels: ✨ Feature, 🧹 Refactor, 📱 UI/UX, 🔗 Network, 🐱 다은, 🎯 UIKit

#111 [Feat] STAMPIT-184 홈화면에서의 미션완료 취소 로직 개선
  StampIt-Project/StampIt-Project/Domain/Entities/Mission.swift
  StampIt-Project/StampIt-Project/Presentation/Common/Component/CustomToastView.swift
  StampIt-Project/StampIt-Project/Presentation/Common/Mapper/MissionMapper.swift
  StampIt-Project/StampIt-Project/Presentation/Home/Common/AssignedMissionCell.swift
  StampIt-Project/StampIt-Project/Presentation/Home/Model/HomeItem.swift
  StampIt-Project/StampIt-Project/Presentation/Home/MyMission/ViewModel/MyMissionViewModel.swift
  StampIt-Project/StampIt-Project/Presentation/Home/ViewController/HomeViewController.swift
  StampIt-Project/StampIt-Project/Presentation/Home/ViewModel/HomeViewModel.swift
Labels: ✨ Feature, 📱 UI/UX, 🐱 다은, 🐛 Bug

#112 [Feat] STAMPIT-201 - 추천 미션 제안 기능 구현
  StampIt-Project/StampIt-Project/Presentation/Mission/View/MissionListViewController.swift
  StampIt-Project/StampIt-Project/Presentation/Mission/View/Subview/MissionListCell.swift
  StampIt-Project/StampIt-Project/Presentation/Mission/ViewModel/MissionListViewModel.swift
Labels: ✨ Feature, 📱 UI/UX, 🎯 UIKit, 🐻 순욱

#110 [Feat] STAMPIT-182 스탬프 상세뷰 데이터 바인딩 및 버그 수정
  StampIt-Project/StampIt-Project/App/DIContainer.swift
  StampIt-Project/StampIt-Project/Data/Entities/Model/StickerFirestore.swift
  StampIt-Project/StampIt-Project/Data/RepositoryImpl/MissionRepositoryImpl.swift
  StampIt-Project/StampIt-Project/Data/RepositoryImpl/MyPageRepositoryImpl.swift
  StampIt-Project/StampIt-Project/Domain/Entities/Mission.swift
  StampIt-Project/StampIt-Project/Domain/Entities/Sticker.swift
  StampIt-Project/StampIt-Project/Domain/Repository/MissionRepository.swift
  StampIt-Project/StampIt-Project/Domain/Repository/MyPageRepository.swift
  StampIt-Project/StampIt-Project/Domain/UseCase/MissionUseCase.swift
  StampIt-Project/StampIt-Project/Domain/UseCase/MyPageUseCase.swift
  StampIt-Project/StampIt-Project/Domain/UseCaseImpl/MissionUseCaseImpl.swift
  StampIt-Project/StampIt-Project/Domain/UseCaseImpl/MyPageUseCaseImpl.swift
  StampIt-Project/StampIt-Project/Presentation/Common/Component/TagView.swift
  StampIt-Project/StampIt-Project/Presentation/Home/View/Subviews/MissionCardCell.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/Enum/Section.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/Model/MissionUI.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/Model/StickerUI.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/Util/DateFormatterUtil.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/Util/StickerUtil.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/View/StampBoard/StampBoardCollectionView.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/View/StampBoard/StampBoardTab.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/View/StampBoard/StampCell.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/ViewController/StampBoardViewController.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/ViewController/StampInfoViewController.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/ViewModel/StampBoardViewModel.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/ViewModel/StampInfoViewModel.swift
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/Red/red300.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Extensions/UILabel+Extension.swift
  StampIt-Project/StampIt-ProjectTests/UseCaseTests/MissionRepositoryTest.swift
Labels: ✨ Feature, 🧹 Refactor, 🐛 Bug, 🦁 하경

#114 [Refactor] STAMPIT-201 - PR 피드백 내용 반영
  StampIt-Project/StampIt-Project/Presentation/Common/Model/Event.swift
  StampIt-Project/StampIt-Project/Presentation/Mission/View/MissionListViewController.swift
  StampIt-Project/StampIt-Project/Presentation/Mission/View/Subview/MissionListCell.swift
  StampIt-Project/StampIt-Project/Presentation/Mission/ViewModel/MissionListViewModel.swift
Labels: 🧹 Refactor, 📱 UI/UX, 🎯 UIKit, 🐻 순욱

#116 [Fix] STAMPIT-222 - 추천 관련 모델 내용 누락
  StampIt-Project/StampIt-Project/Presentation/Common/Model/Event.swift
Labels: 🐛 Bug, 🐻 순욱

#118 [Feat] STAMPIT-227 - NoticeManager 구현
  StampIt-Project/StampIt-Project/Data/DataSources/Manager/Notice/NoticeError.swift
  StampIt-Project/StampIt-Project/Data/DataSources/Manager/Notice/NoticeManager.swift
  StampIt-Project/StampIt-Project/Data/DataSources/Manager/Notification/NotificationManager.swift
  StampIt-Project/StampIt-Project/Data/DataSources/Manager/Notification/SoundManager.swift
  StampIt-Project/StampIt-Project/Data/Entities/Model/DataNoticeFirestore.swift
  StampIt-Project/StampIt-Project/Data/Entities/Query/NoticeQuery.swift
  StampIt-Project/StampIt-Project/Domain/Entities/MissionNotification.swift
  StampIt-Project/StampIt-Project/Domain/Entities/Notice.swift
  StampIt-Project/StampIt-Project/Presentation/Notification/NotificationBanner.swift
Labels: ✨ Feature, 🦊 부용, 🗃 CoreData
