Repository nbcamp-final-team3/stamp-it, pull requests merged in 2025-06, with the labels that each got.

#7 [Chore] STAMPIT-59 폰트, 컬러 에셋 추가
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/Gray/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/Gray/gray300.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/Gray/gray50.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/Gray/gray500.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/Gray/gray600.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/Gray/gray800.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/NeutralGray/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/NeutralGray/neutralGray300.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/NeutralGray/neutralGray400.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/NeutralGray/neutralGray50.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/NeutralGray/neutralGray500.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/NeutralGray/neutralGray900.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/Purple/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/Purple/purple100.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/Red/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/Red/red100.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/Red/red200.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/Red/red400.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/Red/red50.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/Yellow/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/Yellow/yellow100.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/blue/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/blue/blue100.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/untitled/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/untitled/_000000.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/untitled/_1C1B1F.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/untitled/_1E1E1E.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/untitled/_4E4E4E.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/untitled/_55D94B.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/untitled/_777777.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/untitled/_888888.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/untitled/_D7D7D7.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/untitled/_F24949.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/untitled/_F2F2F2.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/untitled/_F7F7F7.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/untitled/_FFFFFF.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Extensions/Font+Extension.swift
  StampIt-Project/StampIt-Project/Resource/Font/Pretendard-Black.otf
  StampIt-Project/StampIt-Project/Resource/Font/Pretendard-Bold.otf
  StampIt-Project/StampIt-Project/Resource/Font/Pretendard-ExtraBold.otf
  StampIt-Project/StampIt-Project/Resource/Font/Pretendard-ExtraLight.otf
  StampIt-Project/StampIt-Project/Resource/Font/Pretendard-Light.otf
  StampIt-Project/StampIt-Project/Resource/Font/Pretendard-Medium.otf
  StampIt-Project/StampIt-Project/Resource/Font/Pretendard-Regular.otf
  StampIt-Project/StampIt-Project/Resource/Font/Pretendard-SemiBold.otf
  StampIt-Project/StampIt-Project/Resource/Font/Pretendard-Thin.otf
  StampIt-Project/StampIt-Project/Resource/Info.plist
Labels: ⚙️ Setting, 📱 UI/UX, 🐱 다은

#8 [Feat] STAMPIT-58 기본버튼 구현
  StampIt-Project/StampIt-Project/Presentation/Common/DefaultButton.swift
Labels: 📱 UI/UX, 🐱 다은, 🎯 UIKit

#6 [Feat] STAMPIT-49 홈화면 상태 관리를 위한 ViewModel 구현
  StampIt-Project/StampIt-Project.xcodeproj/project.pbxproj
  StampIt-Project/StampIt-Project/Domain/Model/Mission.swift
  StampIt-Project/StampIt-Project/Domain/Model/MissionCategory.swift
  StampIt-Project/StampIt-Project/Domain/Model/MissionStatus.swift
  StampIt-Project/StampIt-Project/Domain/Repository/HomeRepository.swift
  StampIt-Project/StampIt-Project/Domain/UseCase/HomeUseCase.swift
  StampIt-Project/StampIt-Project/Presentation/Common/InvitationType.swift
  StampIt-Project/StampIt-Project/Presentation/Common/MissionCategory+Extension.swift
  StampIt-Project/StampIt-Project/Presentation/Common/MissionStatus+Extension.swift
  StampIt-Project/StampIt-Project/Presentation/Common/ViewModelProtocol.swift
  StampIt-Project/StampIt-Project/Presentation/Home/Model/HomeItem.swift
  StampIt-Project/StampIt-Project/Presentation/Home/ViewModel/HomeViewModel.swift
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/Mission/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/Mission/chore.imageset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/Mission/chore.imageset/housekeeping.svg
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/Mission/communication.imageset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/Mission/communication.imageset/community.svg
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/Mission/health.imageset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/Mission/health.imageset/dumbbell.svg
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/Mission/learning.imageset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/Mission/learning.imageset/open book.svg
  StampIt-Project/StampIt-Project/Resource/Extensions/Date+Extension.swift
Labels: ✨ Feature, 🐱 다은

#9 [Feat] STAMPIT-20 미션 뷰
  StampIt-Project/StampIt-Project.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  StampIt-Project/StampIt-Project/Domain/Model/SampleMission.swift
  StampIt-Project/StampIt-Project/Domain/Repository/SampleMissionRepository.swift
  StampIt-Project/StampIt-Project/Domain/UseCase/SampleMissionUseCase.swift
  StampIt-Project/StampIt-Project/Domain/UseCaseImpl/SampleMissionUseCaseImpl.swift
  StampIt-Project/StampIt-Project/Presentation/Mission/Protocol/MissionViewModelProtocol.swift
  StampIt-Project/StampIt-Project/Presentation/Mission/View/AssignMissionViewController.swift
  StampIt-Project/StampIt-Project/Presentation/Mission/View/MissionListViewController.swift
  StampIt-Project/StampIt-Project/Presentation/Mission/View/Subview/MissionListCell.swift
  StampIt-Project/StampIt-Project/Presentation/Mission/ViewModel/AssignMissionViewModel.swift
  StampIt-Project/StampIt-Project/Presentation/Mission/ViewModel/MissionListViewModel.swift
  StampIt-Project/StampIt-Project/Resource/family.json
  StampIt-Project/StampIt-Project/Resource/house.json
Labels: ✨ Feature, 📱 UI/UX, 🎯 UIKit, 🐻 순욱

#12 [Feat] STAMPIT-4 그룹 구성하기 뷰 구현
  StampIt-Project/StampIt-Project/Presentation/Common/DefaultButton.swift
  StampIt-Project/StampIt-Project/Presentation/Home/SelectInvitation/View/SelectInvitationView.swift
  StampIt-Project/StampIt-Project/Presentation/Home/SelectInvitation/View/Subviews/OptionSelectionCard.swift
  StampIt-Project/StampIt-Project/Presentation/Home/SelectInvitation/ViewController/SelectInvitationViewController.swift
  StampIt-Project/StampIt-Project/Presentation/Home/SelectInvitation/ViewModel/SelectInvitationViewModel.swift
  StampIt-Project/StampIt-Project/Presentation/Home/View/HomeView.swift
  StampIt-Project/StampIt-Project/Presentation/Home/View/Subviews/GroupOrganizationView.swift
  StampIt-Project/StampIt-Project/Presentation/Home/ViewController/HomeViewController.swift
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/Mascot/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/Mascot/mascotRed.imageset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/Mascot/mascotRed.imageset/mascotRed.svg
  StampIt-Project/StampIt-Project/Resource/Extensions/UILabel+Extension.swift
Labels: ✨ Feature, 🐱 다은, 🎯 UIKit

#11 [Feat] STAMPIT-18 마이페이지 탭 이동 및 프로필 탭 UI 구현
  StampIt-Project/StampIt-Project/Presentation/MyPage/Constant.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/MyPageHeader.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/MyPageViewController.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/ProfileMenuCell.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/Section.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/StampBoard.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/TabButton.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/UserProfile.swift
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/Gray/gray300.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/Gray/gray50.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/Gray/gray500.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/Gray/gray600.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/Gray/gray800.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/NeutralGray/neutralGray300.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/NeutralGray/neutralGray400.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/NeutralGray/neutralGray50.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/NeutralGray/neutralGray500.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/NeutralGray/neutralGray900.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/untitled/_000000.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/untitled/_1C1B1F.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/untitled/_1E1E1E.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/untitled/_4E4E4E.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Colors/untitled/_777777.colorset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/edit.imageset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/edit.imageset/edit 1.svg
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/edit.imageset/edit 2.svg
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/edit.imageset/edit.svg
Labels: 📱 UI/UX, 🎯 UIKit, 🦁 하경

#14 [Feat] STAMPIT-69 미션 카테고리 필터
  StampIt-Project/StampIt-Project/Domain/Model/MissionCategory.swift
  StampIt-Project/StampIt-Project/Domain/Model/SampleMission.swift
  StampIt-Project/StampIt-Project/Domain/Repository/SampleMissionRepository.swift
  StampIt-Project/StampIt-Project/Presentation/Common/CategoryCell.swift
  StampIt-Project/StampIt-Project/Presentation/Mission/View/MissionListViewController.swift
  StampIt-Project/StampIt-Project/Presentation/Mission/ViewModel/MissionListViewModel.swift
  StampIt-Project/StampIt-Project/Resource/family+category.json
  StampIt-Project/StampIt-Project/Resource/house+category.json
Labels: ✨ Feature, 📱 UI/UX, 🎯 UIKit, 🐻 순욱

#15 [Feat] STAMPIT-25 Create AuthManager, Repository
  StampIt-Project/StampIt-Project.xcodeproj/project.xcworkspace/xcuserdata/by_ios_study.xcuserdatad/UserInterfaceState.xcuserstate
  StampIt-Project/StampIt-Project/App/DIContainer.swift
  StampIt-Project/StampIt-Project/Data/DataSources/AuthError.swift
  StampIt-Project/StampIt-Project/Data/DataSources/AuthManager.swift
  StampIt-Project/StampIt-Project/Data/DataSources/FirestoreError.swift
  StampIt-Project/StampIt-Project/Data/DataSources/FirestoreManager.swift
  StampIt-Project/StampIt-Project/Data/Entities/UserFirestore.swift
  StampIt-Project/StampIt-Project/Data/RepositoryImpl/AuthRepositoryImpl.swift
  StampIt-Project/StampIt-Project/Domain/Entities/AuthDomainModel.swift
  StampIt-Project/StampIt-Project/Domain/Entities/RepositoryError.swift
  StampIt-Project/StampIt-Project/Domain/Repository/AuthRepository.swift
Labels: ✨ Feature, 🦊 부용, 🗃 CoreData

#17 [Feat] STAMPIT-70 마이페이지 스탬프판 탭 UI 구현
  StampIt-Project/StampIt-Project/Domain/Model/Sticker.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/Enum/Constant.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/Enum/Section.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/StampBoard.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/Subview/Profile/ProfileHeader.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/Subview/Profile/ProfileMenuCell.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/Subview/Profile/ProfileTab.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/Subview/StampBoard/DashedLine.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/Subview/StampBoard/StampBoard.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/Subview/StampBoard/StampBoardTab.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/Subview/StampBoard/StampCell.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/Subview/StampBoard/StampSummary.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/Subview/TabButton.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/ViewController/MyPageViewController+TableView.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/ViewController/MyPageViewController.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/ViewModel/MyPageViewModel.swift
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/stampGray.imageset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/stampGray.imageset/stampGray 1.svg
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/stampGray.imageset/stampGray 2.svg
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/stampGray.imageset/stampGray.svg
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/stampRed.imageset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/stampRed.imageset/stampRed 1.svg
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/stampRed.imageset/stampRed 2.svg
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/stampRed.imageset/stampRed.svg
Labels: 📱 UI/UX, 🎯 UIKit, 🦁 하경

#18 [Feat] STAMPIT-71 미션 뷰 - 데이터 레이어 연동
  StampIt-Project/StampIt-Project/Data/RepositoryImpl/MissionRepositoryImpl.swift
  StampIt-Project/StampIt-Project/Data/RepositoryImpl/MissionRepositoryTest.swift
  StampIt-Project/StampIt-Project/Domain/Repository/MissionRepository.swift
  StampIt-Project/StampIt-Project/Domain/Repository/SampleMissionRepository.swift
  StampIt-Project/StampIt-Project/Domain/UseCase/MissionUseCase.swift
  StampIt-Project/StampIt-Project/Domain/UseCase/SampleMissionUseCase.swift
  StampIt-Project/StampIt-Project/Domain/UseCaseImpl/MissionUseCaseImpl.swift
  StampIt-Project/StampIt-Project/Domain/UseCaseImpl/SampleMissionUseCaseImpl.swift
  StampIt-Project/StampIt-Project/Presentation/Mission/ViewModel/AssignMissionViewModel.swift
  StampIt-Project/StampIt-Project/Presentation/Mission/ViewModel/MissionListViewModel.swift
Labels: ✨ Feature, 🎯 UIKit, 🐻 순욱

#19 [Feat] STAMPIT-28- Google Login UseCase, VM, VC
  .gitignore
  StampIt-Project/StampIt-Project.xcodeproj/project.pbxproj
  StampIt-Project/StampIt-Project/App/DIContainer.swift
  StampIt-Project/StampIt-Project/App/SceneDelegate.swift
  StampIt-Project/StampIt-Project/Data/Entities/UserFirestore.swift
  StampIt-Project/StampIt-Project/Data/RepositoryImpl/AuthRepositoryImpl.swift
  StampIt-Project/StampIt-Project/Domain/Entities/AuthDomainModel.swift
  StampIt-Project/StampIt-Project/Domain/UseCase/LoginUseCase.swift
  StampIt-Project/StampIt-Project/Domain/UseCaseImpl/LoginUseCaseImpl.swift
  StampIt-Project/StampIt-Project/Presentation/Login/ViewController/LoginViewController.swift
  StampIt-Project/StampIt-Project/Presentation/Login/ViewModel/LoginViewModel.swift
  StampIt-Project/StampIt-Project/Presentation/TestViewController.swift
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/CharacterImage/MascotCharacterSad.imageset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/CharacterImage/MascotCharacterSad.imageset/MascotCharacterSad 1.pdf
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/CharacterImage/MascotCharacterSad.imageset/MascotCharacterSad 2.pdf
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/CharacterImage/MascotCharacterSad.imageset/MascotCharacterSad.pdf
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/Logo/AppLogo.imageset/AppLogo 1.pdf
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/Logo/AppLogo.imageset/AppLogo 2.pdf
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/Logo/AppLogo.imageset/AppLogo.pdf
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/Logo/AppLogo.imageset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/Logo/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/Logo/GoogleLogo.imageset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/Logo/GoogleLogo.imageset/icons8-google-144.png
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/Logo/GoogleLogo.imageset/icons8-google-48.png
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/Logo/GoogleLogo.imageset/icons8-google-96.png
  StampIt-Project/StampIt-Project/Resource/Extensions/String+Extension.swift
  StampIt-Project/StampIt-Project/Resource/Info.plist
  StampIt-Project/StampIt-Project/StampIt-Project.entitlements
  StampIt-Project/StampIt-ProjectTests/UseCaseTests/LoginUseCaseTests.swift
  StampIt-Project/StampIt-ProjectTests/UseCaseTests/MockAuthRepository.swift
  StampIt-Project/StampIt-ProjectTests/UseCaseTests/TestFixtures.swift
Labels: ✨ Feature, 📱 UI/UX, 🧪 Test, 🦊 부용

#20 [Fix] STAMPIT-70-1 UUID 을 String 타입으로 변경
  StampIt-Project/StampIt-Project/Data/Entities/StickerFirestore.swift
  StampIt-Project/StampIt-Project/Domain/Model/Sticker.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/Enum/Constant.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/ViewController/MyPageViewController.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/ViewModel/MyPageViewModel.swift
Labels: 🐛 Bug, 🦁 하경

#21 [Feat] STAMPIT-77 - 서치바, 카테고리 필터 UI 개선
  StampIt-Project/StampIt-Project/Presentation/Common/CategoryCell.swift
  StampIt-Project/StampIt-Project/Presentation/Mission/View/MissionListViewController.swift
Labels: ✨ Feature, 📱 UI/UX, 🎯 UIKit, 🐻 순욱

#29 [Feat] STAMPIT-76 스탬프판 지그재그 로직
  StampIt-Project/StampIt-Project/Presentation/MyPage/Enum/Constant.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/View/StampBoard/StampSummary.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/ViewController/MyPageViewController+TableView.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/ViewController/MyPageViewController.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/ViewModel/MyPageViewModel.swift
Labels: ✨ Feature, 📱 UI/UX, 🎯 UIKit, 🦁 하경

#31 [Feat] STAMPIT-78 대시보드 데이터 바인딩
  StampIt-Project/StampIt-Project/App/DIContainer.swift
  StampIt-Project/StampIt-Project/Data/DataSources/FirestoreManager.swift
  StampIt-Project/StampIt-Project/Data/Entities/MissionFirestore.swift
  StampIt-Project/StampIt-Project/Data/RepositoryImpl/AuthRepositoryImpl.swift
  StampIt-Project/StampIt-Project/Data/RepositoryImpl/HomeRepositoryImpl.swift
  StampIt-Project/StampIt-Project/Domain/Model/MissionCategory.swift
  StampIt-Project/StampIt-Project/Domain/Model/MissionStatus.swift
  StampIt-Project/StampIt-Project/Domain/Repository/HomeRepository.swift
  StampIt-Project/StampIt-Project/Domain/UseCase/HomeUseCase.swift
  StampIt-Project/StampIt-Project/Domain/UseCaseImpl/HomeUseCaseImpl.swift
  StampIt-Project/StampIt-Project/Presentation/Home/Common/MemberCompactCell.swift
  StampIt-Project/StampIt-Project/Presentation/Home/Model/HomeItem.swift
  StampIt-Project/StampIt-Project/Presentation/Home/View/HomeView.swift
  StampIt-Project/StampIt-Project/Presentation/Home/View/Subviews/DashboardHeader.swift
  StampIt-Project/StampIt-Project/Presentation/Home/View/Subviews/GroupDashBoardView.swift
  StampIt-Project/StampIt-Project/Presentation/Home/View/Subviews/MissionCardCell.swift
  StampIt-Project/StampIt-Project/Presentation/Home/ViewController/HomeViewController.swift
  StampIt-Project/StampIt-Project/Presentation/Home/ViewModel/HomeViewModel.swift
Labels: ✨ Feature, 📱 UI/UX, 🐱 다은, 🎯 UIKit

#30 [Feat] STAMPIT-82 - Sticker CURD 추가 구현
  StampIt-Project/StampIt-Project/Data/DataSources/FirestoreManager.swift
Labels: ✨ Feature, 🧹 Refactor, 🦊 부용, 🗃 CoreData

#32 [Fix] STAMPIT-95 - FirestoreManager Invite 수정, 자동 로그인 구현
  StampIt-Project/StampIt-Project/App/SceneDelegate.swift
  StampIt-Project/StampIt-Project/Data/DataSources/FirestoreManager.swift
  StampIt-Project/StampIt-Project/Data/Entities/GroupFirestore.swift
  StampIt-Project/StampIt-Project/Data/Entities/InviteFirestore.swift
  StampIt-Project/StampIt-Project/Data/Entities/MemberFirestore.swift
  StampIt-Project/StampIt-Project/Data/Entities/UserFirestore.swift
  StampIt-Project/StampIt-Project/Data/RepositoryImpl/AuthRepositoryImpl.swift
  StampIt-Project/StampIt-Project/Domain/Model/Invite.swift
  StampIt-Project/StampIt-Project/Domain/Repository/AuthRepository.swift
  StampIt-Project/StampIt-Project/Domain/UseCaseImpl/LoginUseCaseImpl.swift
  StampIt-Project/StampIt-Project/Presentation/Common/UserCache.swift
  StampIt-Project/StampIt-Project/Presentation/Common/WindowTransitionManager.swift
  StampIt-Project/StampIt-Project/Presentation/Launch/ViewController/LaunchViewController.swift
  StampIt-Project/StampIt-Project/Presentation/Login/ViewController/LoginViewController.swift
Labels: ✨ Feature, 🧹 Refactor, 🦊 부용, 🗃 CoreData

#34 [Fix] - deleteGroup 수정
  StampIt-Project/StampIt-Project/Data/DataSources/FirestoreManager.swift
Labels: 🧹 Refactor, 🦊 부용, 🐛 Bug

#37 [Feat] STAMPIT-84 멤버 미션 더보기 화면 구현
  StampIt-Project/StampIt-Project/App/DIContainer.swift
  StampIt-Project/StampIt-Project/Domain/UseCase/MemberMissionUseCase.swift
  StampIt-Project/StampIt-Project/Domain/UseCaseImpl/MemberMissionUseCaseImpl.swift
  StampIt-Project/StampIt-Project/Presentation/Home/MemberMission/Model/MemberMissionItem.swift
  StampIt-Project/StampIt-Project/Presentation/Home/MemberMission/View/MemberMissionView.swift
  StampIt-Project/StampIt-Project/Presentation/Home/MemberMission/ViewController/MemberMissionViewController.swift
  StampIt-Project/StampIt-Project/Presentation/Home/MemberMission/ViewModel/MemberMissionViewModel.swift
  StampIt-Project/StampIt-Project/Presentation/Home/MyMission/ViewModel/MyMissionViewModel.swift
  StampIt-Project/StampIt-Project/Presentation/Home/View/HomeView.swift
  StampIt-Project/StampIt-Project/Presentation/Home/View/Subviews/GroupDashBoardView.swift
  StampIt-Project/StampIt-Project/Presentation/Home/ViewController/HomeViewController.swift
  StampIt-Project/StampIt-Project/Presentation/Home/ViewModel/HomeViewModel.swift
Labels: ✨ Feature, 📱 UI/UX, 🔗 Network, 🐱 다은, 🎯 UIKit

#33 [Feat] STAMPIT-77 - 미션 화면 UI 개선
  StampIt-Project/StampIt-Project/Presentation/Mission/View/AssignMissionViewController.swift
  StampIt-Project/StampIt-Project/Presentation/Mission/View/Subview/MissionListCell.swift
Labels: 🧹 Refactor, 📱 UI/UX, 🎯 UIKit, 🐻 순욱

#38 [Feat] STAMPIT-97 - 로그아웃, 서비스탈퇴, 그룹탈퇴 구현
  StampIt-Project/StampIt-Project/App/DIContainer.swift
  StampIt-Project/StampIt-Project/Data/DataSources/AuthManager.swift
  StampIt-Project/StampIt-Project/Data/DataSources/FirestoreManager.swift
  StampIt-Project/StampIt-Project/Data/RepositoryImpl/AuthRepositoryImpl.swift
  StampIt-Project/StampIt-Project/Domain/Entities/GroupExitError.swift
  StampIt-Project/StampIt-Project/Domain/Entities/LeaderAction.swift
  StampIt-Project/StampIt-Project/Domain/Entities/RepositoryError.swift
  StampIt-Project/StampIt-Project/Domain/Repository/AuthRepository.swift
  StampIt-Project/StampIt-Project/Domain/UseCase/AccountManageUseCase.swift
  StampIt-Project/StampIt-Project/Domain/UseCase/LoginUseCase.swift
  StampIt-Project/StampIt-Project/Domain/UseCaseImpl/AccountManageUseCaseImpl.swift
  StampIt-Project/StampIt-Project/Domain/UseCaseImpl/LoginUseCaseImpl.swift
  StampIt-Project/StampIt-Project/Presentation/Login/ViewController/LoginViewController.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/Enum/Section.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/View/Profile/ProfileMenuCell.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/View/Profile/ProfileTab.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/ViewController/MyPageViewController+TableView.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/ViewController/MyPageViewController.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/ViewModel/MyPageViewModel.swift
Labels: ✨ Feature, 🧹 Refactor, 🦊 부용, 🗃 CoreData

#36 [Fix] STAMPIT-94 변경된 Firestore Sticker 에 맞춰 StampBoard, StampSummary 뷰 데이터 바인딩
  StampIt-Project/StampIt-Project/Data/DataSources/FirestoreManager.swift
  StampIt-Project/StampIt-Project/Data/Entities/StickerFirestore.swift
  StampIt-Project/StampIt-Project/Data/RepositoryImpl/MyPageRepositoryImpl.swift
  StampIt-Project/StampIt-Project/Domain/Model/Sticker.swift
  StampIt-Project/StampIt-Project/Domain/Repository/MyPageRepository.swift
  StampIt-Project/StampIt-Project/Domain/UseCase/MyPageUseCase.swift
  StampIt-Project/StampIt-Project/Domain/UseCaseImpl/MyPageUseCaseImpl.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/Enum/Constant.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/Enum/Section.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/View/StampBoard/DashedLine.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/View/StampBoard/StampBoardTab.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/View/StampBoard/StampSummary.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/ViewController/MyPageViewController.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/ViewModel/MyPageViewModel.swift
Labels: ✨ Feature, 🧹 Refactor, 🗃 CoreData, 🐛 Bug, 🦁 하경

#45 [Feat] STAMPIT-98 미션 완료 후 취소 구현
  StampIt-Project/StampIt-Project/App/DIContainer.swift
  StampIt-Project/StampIt-Project/Data/DataSources/FirestoreManager.swift
  StampIt-Project/StampIt-Project/Data/Entities/MemberFirestore.swift
  StampIt-Project/StampIt-Project/Data/Entities/StickerFirestore.swift
  StampIt-Project/StampIt-Project/Data/RepositoryImpl/HomeRepositoryImpl.swift
  StampIt-Project/StampIt-Project/Data/RepositoryImpl/MissionRepositoryTest.swift
  StampIt-Project/StampIt-Project/Domain/Model/Member.swift
  StampIt-Project/StampIt-Project/Domain/Model/Mission.swift
  StampIt-Project/StampIt-Project/Domain/Model/Sticker.swift
  StampIt-Project/StampIt-Project/Domain/Repository/HomeRepository.swift
  StampIt-Project/StampIt-Project/Domain/UseCase/HomeUseCase.swift
  StampIt-Project/StampIt-Project/Domain/UseCase/MyMissionUseCase.swift
  StampIt-Project/StampIt-Project/Domain/UseCaseImpl/HomeUseCaseImpl.swift
  StampIt-Project/StampIt-Project/Domain/UseCaseImpl/LoginUseCaseImpl.swift
  StampIt-Project/StampIt-Project/Domain/UseCaseImpl/MyMissionUseCaseImpl.swift
  StampIt-Project/StampIt-Project/Presentation/Common/Component/CustomToastView.swift
  StampIt-Project/StampIt-Project/Presentation/Home/Common/AssignedMissionCell.swift
  StampIt-Project/StampIt-Project/Presentation/Home/MemberMission/ViewModel/MemberMissionViewModel.swift
  StampIt-Project/StampIt-Project/Presentation/Home/MyMission/View/MyMissionView.swift
  StampIt-Project/StampIt-Project/Presentation/Home/MyMission/ViewController/MyMissionViewController.swift
  StampIt-Project/StampIt-Project/Presentation/Home/MyMission/ViewModel/MyMissionViewModel.swift
  StampIt-Project/StampIt-Project/Presentation/Home/View/HomeView.swift
  StampIt-Project/StampIt-Project/Presentation/Home/View/Subviews/GroupDashBoardView.swift
  StampIt-Project/StampIt-Project/Presentation/Home/ViewController/HomeViewController.swift
  StampIt-Project/StampIt-Project/Presentation/Home/ViewModel/HomeViewModel.swift
  StampIt-Project/StampIt-Project/Presentation/Invite/ViewController/ReceiveInviteViewController.swift
  StampIt-Project/StampIt-Project/Presentation/Invite/ViewController/SendInviteViewController.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/ViewModel/MyPageViewModel.swift
  StampIt-Project/StampIt-Project/Resource/Extensions/Date+Extension.swift
  StampIt-Project/StampIt-Project/Resource/Extensions/String+Extension.swift
  StampIt-Project/StampIt-Project/Resource/GoogleService-Info.plist
Labels: ✨ Feature, 📱 UI/UX, 🔗 Network, 🐱 다은, 🎯 UIKit

#52 [Fix] STAMPIT-111 스탬프판 UI 변경 적용
  StampIt-Project/StampIt-Project/Data/Entities/StickerFirestore.swift
  StampIt-Project/StampIt-Project/Presentation/Common/MainTabBarController.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/View/StampBoard/StampBoard.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/View/StampBoard/StampBoardTab.swift
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/Stamp/stampGray.imageset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/Stamp/stampGray.imageset/Group 46.svg
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/Stamp/stampGray.imageset/Group 47.svg
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/Stamp/stampGray.imageset/Group 48.svg
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/Stamp/stampGray.imageset/stampGray 1.svg
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/Stamp/stampGray.imageset/stampGray 2.svg
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/Stamp/stampGray.imageset/stampGray.svg
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/Stamp/stampRed.imageset/Contents.json
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/Stamp/stampRed.imageset/selectedRed 1.svg
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/Stamp/stampRed.imageset/selectedRed 2.svg
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/Stamp/stampRed.imageset/selectedRed.svg
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/Stamp/stampRed.imageset/stampRed 1.svg
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/Stamp/stampRed.imageset/stampRed 2.svg
  StampIt-Project/StampIt-Project/Resource/Assets.xcassets/Image/Stamp/stampRed.imageset/stampRed.svg
Labels: 🧹 Refactor, 📱 UI/UX, 🦁 하경

#51 [Feat] STAMPIT-108 멤버 정보 업데이트 시 랭킹 동기화 및 최신 디자인 가이드 반영
  StampIt-Project/StampIt-Project.xcodeproj/project.pbxproj
  StampIt-Project/StampIt-Project/Data/DataSources/FirestoreManager.swift
  StampIt-Project/StampIt-Project/Data/Entities/MemberFirestore.swift
  StampIt-Project/StampIt-Project/Data/RepositoryImpl/EditProfileRepositoryImpl.swift
  StampIt-Project/StampIt-Project/Data/RepositoryImpl/EditProfileRepositoryTest.swift
  StampIt-Project/StampIt-Project/Data/RepositoryImpl/HomeRepositoryImpl.swift
  StampIt-Project/StampIt-Project/Data/RepositoryImpl/MissionRepositoryTest.swift
  StampIt-Project/StampIt-Project/Data/RepositoryImpl/MyPageRepositoryImpl.swift
  StampIt-Project/StampIt-Project/Domain/Model/Member.swift
  StampIt-Project/StampIt-Project/Domain/Repository/EditProfileRepository.swift
  StampIt-Project/StampIt-Project/Domain/Repository/MyPageRepository.swift
  StampIt-Project/StampIt-Project/Domain/UseCase/EditProfileUseCase.swift
  StampIt-Project/StampIt-Project/Domain/UseCase/MyPageUseCase.swift
  StampIt-Project/StampIt-Project/Domain/UseCaseImpl/EditProfileUseCaseImpl.swift
  StampIt-Project/StampIt-Project/Domain/UseCaseImpl/LoginUseCaseImpl.swift
  StampIt-Project/StampIt-Project/Domain/UseCaseImpl/MyPageUseCaseImpl.swift
  StampIt-Project/StampIt-Project/Presentation/Common/Component/DefaultButton.swift
  StampIt-Project/StampIt-Project/Presentation/Common/Component/NoResultsView.swift
  StampIt-Project/StampIt-Project/Presentation/Home/Common/MemberCompactCell.swift
  StampIt-Project/StampIt-Project/Presentation/Home/MemberMission/View/MemberMissionView.swift
  StampIt-Project/StampIt-Project/Presentation/Home/MemberMission/ViewController/MemberMissionViewController.swift
  StampIt-Project/StampIt-Project/Presentation/Home/MemberMission/ViewModel/MemberMissionViewModel.swift
  StampIt-Project/StampIt-Project/Presentation/Home/Model/HomeItem.swift
  StampIt-Project/StampIt-Project/Presentation/Home/MyMission/View/MyMissionView.swift
  StampIt-Project/StampIt-Project/Presentation/Home/MyMission/ViewController/MyMissionViewController.swift
  StampIt-Project/StampIt-Project/Presentation/Home/MyMission/ViewModel/MyMissionViewModel.swift
  StampIt-Project/StampIt-Project/Presentation/Home/View/HomeView.swift
  StampIt-Project/StampIt-Project/Presentation/Home/View/Subviews/GroupOrganizationView.swift
  StampIt-Project/StampIt-Project/Presentation/Home/ViewController/HomeViewController.swift
  StampIt-Project/StampIt-Project/Presentation/Home/ViewModel/HomeViewModel.swift
  StampIt-Project/StampIt-Project/Presentation/Mission/View/MissionListViewController.swift
  StampIt-Project/StampIt-Project/Presentation/Mission/View/Subview/NoResultsView.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/ViewModel/EditProfileViewModel.swift
  StampIt-Project/StampIt-Project/Resource/Extensions/UILabel+Extension.swift
Labels: ✨ Feature, 📱 UI/UX, 🔗 Network, 🐱 다은, 🐛 Bug, 🎯 UIKit

#55 [Fix] 새 미션 만들 때 전달 정보 nickname -> userID로 변경
  StampIt-Project/StampIt-Project/Presentation/Mission/ViewModel/AssignMissionViewModel.swift
Labels: 🐛 Bug, 🐻 순욱

#54 [Feat] STAMPIT-109 토스트 메세지 실패 경우 추가
  StampIt-Project/StampIt-Project/Presentation/Common/Component/CustomToastView.swift
  StampIt-Project/StampIt-Project/Presentation/Home/MyMission/ViewController/MyMissionViewController.swift
  StampIt-Project/StampIt-Project/Presentation/Home/ViewController/HomeViewController.swift
  StampIt-Project/StampIt-Project/Presentation/Invite/ViewController/ReceiveInviteViewController.swift
  StampIt-Project/StampIt-Project/Presentation/Invite/ViewController/SendInviteViewController.swift
  StampIt-Project/StampIt-Project/Presentation/Invite/ViewModel/ReceiveInviteViewModel.swift
  StampIt-Project/StampIt-Project/Presentation/Invite/ViewModel/SendInviteViewModel.swift
Labels: ✨ Feature, 🐯 주형, 🎯 UIKit

#57 [Setting] STAMPIT-112 - 다국어 설정
  StampIt-Project/StampIt-Project/Data/DataSources/AuthError.swift
  StampIt-Project/StampIt-Project/Data/RepositoryImpl/AuthRepositoryImpl.swift
  StampIt-Project/StampIt-Project/Presentation/Login/ViewController/LoginViewController.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/ViewController/MyPageViewController.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/ViewModel/MyPageViewModel.swift
  StampIt-Project/StampIt-Project/Resource/en.lproj/Localizable.strings
  StampIt-Project/StampIt-Project/Resource/ko.lproj/Localizable.strings
Labels: 🚀 Deploy, 🦊 부용, 🐛 Bug

#58 [Fix] 미션 화면에서 키보드 내려가지 않는 현상 해결
  StampIt-Project/StampIt-Project/Presentation/Mission/View/MissionListViewController.swift
Labels: 📱 UI/UX, 🐛 Bug, 🐻 순욱

#59 [Fix] STAMPIT-112 - 애플 로그인 오류 수정 및 테스팅 배포 추가 세팅
  StampIt-Project/StampIt-Project.xcodeproj/project.pbxproj
  StampIt-Project/StampIt-Project/App/DIContainer.swift
  StampIt-Project/StampIt-Project/Data/DataSources/AuthManager.swift
  StampIt-Project/StampIt-Project/Data/RepositoryImpl/AuthRepositoryImpl.swift
  StampIt-Project/StampIt-Project/Data/RepositoryImpl/EditProfileRepositoryTest.swift
  StampIt-Project/StampIt-Project/Presentation/Login/ViewController/LoginViewController.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/ViewModel/EditProfileViewModel.swift
Labels: 🚀 Deploy, 🦊 부용, 🐛 Bug

#66 [Fix] STAMPIT-114 미션 셀 동적 레이아웃 및 UI 개선, 랭킹 개인 표기 추가 & 버그 수정
  StampIt-Project/StampIt-Project/Domain/UseCaseImpl/HomeUseCaseImpl.swift
  StampIt-Project/StampIt-Project/Presentation/Home/Common/AssignedMissionCell.swift
  StampIt-Project/StampIt-Project/Presentation/Home/Common/CompletionStateButton.swift
  StampIt-Project/StampIt-Project/Presentation/Home/Common/MemberCompactCell.swift
  StampIt-Project/StampIt-Project/Presentation/Home/Common/TagView.swift
  StampIt-Project/StampIt-Project/Presentation/Home/MemberMission/View/MemberMissionView.swift
  StampIt-Project/StampIt-Project/Presentation/Home/MyMission/View/MyMissionView.swift
  StampIt-Project/StampIt-Project/Presentation/Home/View/Subviews/DashboardHeader.swift
  StampIt-Project/StampIt-Project/Presentation/Home/View/Subviews/GroupDashBoardView.swift
  StampIt-Project/StampIt-Project/Presentation/Home/View/Subviews/MissionCardCell.swift
  StampIt-Project/StampIt-Project/Presentation/Home/ViewModel/HomeViewModel.swift
Labels: 🧹 Refactor, 📱 UI/UX, 🐱 다은, 🐛 Bug, 🎯 UIKit

#67 [Fix] STAMPIT-136 스탬프판 유지보수
  StampIt-Project/StampIt-Project/Presentation/MyPage/Enum/Constant.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/Enum/Section.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/View/StampBoard/DashedLine.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/View/StampBoard/StampBoardCollectionView.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/View/StampBoard/StampBoardTab.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/View/StampBoard/StampCell.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/View/StampBoard/SummaryCell.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/ViewController/MyPageViewController.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/ViewModel/MyPageViewModel.swift
Labels: 🧹 Refactor, 📱 UI/UX, 🐛 Bug, 🦁 하경

#68 [Feat] STAMPIT-121 닉네임 5자 제한 로직 추가, 소소한 리팩토링
  StampIt-Project/StampIt-Project.xcodeproj/project.pbxproj
  StampIt-Project/StampIt-Project/Presentation/Mission/View/AssignMissionViewController.swift
  StampIt-Project/StampIt-Project/Presentation/Mission/View/MissionListViewController.swift
  StampIt-Project/StampIt-Project/Presentation/Mission/ViewModel/MissionListViewModel.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/ViewController/EditProfileViewController.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/ViewModel/EditProfileViewModel.swift
  StampIt-Project/StampIt-ProjectTests/UseCaseTests/EditProfileRepositoryTest.swift
  StampIt-Project/StampIt-ProjectTests/UseCaseTests/MissionRepositoryTest.swift
Labels: ✨ Feature, 📱 UI/UX, 🐛 Bug, 🎯 UIKit, 🐻 순욱

#69 [Feat] STAMPIT-139 마이페이지 스와이프하여 탭 이동
  StampIt-Project/StampIt-Project/App/DIContainer.swift
  StampIt-Project/StampIt-Project/Domain/UseCase/MyPageUseCase.swift
  StampIt-Project/StampIt-Project/Domain/UseCaseImpl/MyPageUseCaseImpl.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/Enum/Constant.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/ViewController/MyPageViewController.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/ViewController/ProfileViewController+TableView.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/ViewController/ProfileViewController.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/ViewController/StampBoardViewController.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/ViewModel/MyPageViewModel.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/ViewModel/ProfileViewModel.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/ViewModel/StampBoardViewModel.swift
Labels: ✨ Feature, 🧹 Refactor, 📱 UI/UX, 🎯 UIKit, 🦁 하경

#70 [Refactor] STAMPIT-161 홈 유즈케이스 및 뷰모델 리팩토링
  StampIt-Project/StampIt-Project/App/DIContainer.swift
  StampIt-Project/StampIt-Project/Data/RepositoryImpl/TestRepositoryImpl.swift
  StampIt-Project/StampIt-Project/Domain/Entities/Errors/GroupExitError.swift
  StampIt-Project/StampIt-Project/Domain/Entities/Errors/RepositoryError.swift
  StampIt-Project/StampIt-Project/Domain/Entities/Errors/UseCaseError.swift
  StampIt-Project/StampIt-Project/Domain/Entities/Group.swift
  StampIt-Project/StampIt-Project/Domain/Entities/Invite.swift
  StampIt-Project/StampIt-Project/Domain/Entities/Member.swift
  StampIt-Project/StampIt-Project/Domain/Entities/Mission.swift
  StampIt-Project/StampIt-Project/Domain/Entities/MissionCategory.swift
  StampIt-Project/StampIt-Project/Domain/Entities/MissionStatus.swift
  StampIt-Project/StampIt-Project/Domain/Entities/SampleMission.swift
  StampIt-Project/StampIt-Project/Domain/Entities/Sticker.swift
  StampIt-Project/StampIt-Project/Domain/Entities/StickerBoard.swift
  StampIt-Project/StampIt-Project/Domain/Entities/User.swift
  StampIt-Project/StampIt-Project/Domain/Model/Mission.swift
  StampIt-Project/StampIt-Project/Domain/Model/StickerBoard.swift
  StampIt-Project/StampIt-Project/Domain/Repository/TestRepository.swift
  StampIt-Project/StampIt-Project/Domain/Service/MissionExpirationService.swift
  StampIt-Project/StampIt-Project/Domain/ServiceImpl/MissionExpirationServiceImpl.swift
  StampIt-Project/StampIt-Project/Domain/UseCase/HomeUseCase.swift
  StampIt-Project/StampIt-Project/Domain/UseCase/MemberMissionUseCase.swift
  StampIt-Project/StampIt-Project/Domain/UseCase/MyMissionUseCase.swift
  StampIt-Project/StampIt-Project/Domain/UseCase/RankingUseCase.swift
  StampIt-Project/StampIt-Project/Domain/UseCase/TestUseCase.swift
  StampIt-Project/StampIt-Project/Domain/UseCaseImpl/HomeUseCaseImpl.swift
  StampIt-Project/StampIt-Project/Domain/UseCaseImpl/MemberMissionUseCaseImpl.swift
  StampIt-Project/StampIt-Project/Domain/UseCaseImpl/MyMissionUseCaseImpl.swift
  StampIt-Project/StampIt-Project/Domain/UseCaseImpl/RankingUseCaseImpl.swift
  StampIt-Project/StampIt-Project/Domain/UseCaseImpl/TestUseCaseImpl.swift
  StampIt-Project/StampIt-Project/Presentation/Common/Manager/NavigationManager.swift
  StampIt-Project/StampIt-Project/Presentation/Common/Manager/WindowTransitionManager.swift
  StampIt-Project/StampIt-Project/Presentation/Common/Mapper/MemberMapper.swift
  StampIt-Project/StampIt-Project/Presentation/Common/Mapper/MissionMapper.swift
  StampIt-Project/StampIt-Project/Presentation/Common/Mapper/Protocol/MemberMapping.swift
  StampIt-Project/StampIt-Project/Presentation/Common/Mapper/Protocol/MissionMapping.swift
  StampIt-Project/StampIt-Project/Presentation/Home/Common/AssignedMissionCell.swift
  StampIt-Project/StampIt-Project/Presentation/Home/MemberMission/Model/MemberMissionItem.swift
  StampIt-Project/StampIt-Project/Presentation/Home/MemberMission/ViewModel/MemberMissionViewModel.swift
  StampIt-Project/StampIt-Project/Presentation/Home/Model/HomeItem.swift
  StampIt-Project/StampIt-Project/Presentation/Home/MyMission/Model/MyMissionItem.swift
  StampIt-Project/StampIt-Project/Presentation/Home/MyMission/ViewModel/MyMissionViewModel.swift
  StampIt-Project/StampIt-Project/Presentation/Home/View/HomeView.swift
  StampIt-Project/StampIt-Project/Presentation/Home/View/Subviews/GroupDashBoardView.swift
  StampIt-Project/StampIt-Project/Presentation/Home/View/Subviews/MissionCardCell.swift
  StampIt-Project/StampIt-Project/Presentation/Home/ViewController.swift
  StampIt-Project/StampIt-Project/Presentation/Home/ViewController/HomeViewController.swift
  StampIt-Project/StampIt-Project/Presentation/Home/ViewModel/HomeViewModel.swift
Labels: 🧹 Refactor, 🐱 다은

#73 [Refactor] STAMPIT-164 미션/내정보수정 화면 리팩토링
  StampIt-Project/StampIt-Project/Presentation/Mission/View/AssignMissionViewController.swift
  StampIt-Project/StampIt-Project/Presentation/Mission/View/MissionListViewController.swift
  StampIt-Project/StampIt-Project/Presentation/Mission/View/Subview/DueDateView.swift
  StampIt-Project/StampIt-Project/Presentation/Mission/View/Subview/MissionListCell.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/ViewController/EditProfileViewController.swift
Labels: 🧹 Refactor, 📱 UI/UX, 🧑‍🎨 SwiftUI, 🐻 순욱

#74 [Fix] STAMPIT-129 - 홈화면에서 미완료 미션 조회할 수 있도록 미션 쿼리, 매니저 수정
  StampIt-Project/StampIt-Project/Data/DataSources/Manager/Mission/MissionManager.swift
  StampIt-Project/StampIt-Project/Data/Entities/Query/MissionQuery.swift
Labels: 🦊 부용, 🗃 CoreData, 🐛 Bug

#75 [Feat] STAMPIT-130 대시보드에서의 멤버별 미션 필터링 구현 등
  StampIt-Project/StampIt-Project.xcodeproj/xcshareddata/xcschemes/StampIt-Project.xcscheme
  StampIt-Project/StampIt-Project/Domain/ServiceImpl/MissionExpirationServiceImpl.swift
  StampIt-Project/StampIt-Project/Domain/UseCase/MyMissionUseCase.swift
  StampIt-Project/StampIt-Project/Domain/UseCaseImpl/MyMissionUseCaseImpl.swift
  StampIt-Project/StampIt-Project/Presentation/Common/Component/FilterCell.swift
  StampIt-Project/StampIt-Project/Presentation/Home/Model/HomeItem.swift
  StampIt-Project/StampIt-Project/Presentation/Home/View/HomeView.swift
  StampIt-Project/StampIt-Project/Presentation/Home/View/Subviews/GroupDashBoardView.swift
  StampIt-Project/StampIt-Project/Presentation/Home/ViewController/HomeViewController.swift
  StampIt-Project/StampIt-Project/Presentation/Home/ViewModel/HomeViewModel.swift
  StampIt-Project/StampIt-Project/Presentation/Mission/View/MissionListViewController.swift
  StampIt-Project/StampIt-Project/Resource/Extensions/Date+Extension.swift
  StampIt-Project/StampIt-Project/Resource/Extensions/NSCollectionLayoutSection+Extension.swift
Labels: ✨ Feature, 🐱 다은, 🐛 Bug

#76 [Feat] STAMPIT-171 - 닉네임 중복 체크 로직 추가
  StampIt-Project/StampIt-Project/Data/RepositoryImpl/EditProfileRepositoryImpl.swift
  StampIt-Project/StampIt-Project/Domain/Repository/EditProfileRepository.swift
  StampIt-Project/StampIt-Project/Domain/UseCase/EditProfileUseCase.swift
  StampIt-Project/StampIt-Project/Domain/UseCaseImpl/EditProfileUseCaseImpl.swift
  StampIt-Project/StampIt-Project/Presentation/Mission/ViewModel/AssignMissionViewModel.swift
  StampIt-Project/StampIt-Project/Presentation/MyPage/ViewModel/EditProfileViewModel.swift
  StampIt-Project/StampIt-ProjectTests/UseCaseTests/EditProfileRepositoryTest.swift
Labels: ✨ Feature, 🧹 Refactor, 🎯 UIKit, 🐻 순욱

#78 [Feat] STAMPIT-118 멤버 관리하기 기능 구현
  StampIt-Project/StampIt-Project/App/DIContainer.swift
  StampIt-Project/StampIt-Project/Data/Entities/Query/MembershipQuery.swift
  StampIt-Project/StampIt-Project/Data/RepositoryImpl/AccountManageRepositoryImpl.swift
  StampIt-Project/StampIt-Project/Data/RepositoryImpl/GroupManageRepositoryImpl.swift
  StampIt-Project/StampIt-Project/Domain/Entities/Errors/GroupUseCaseError.swift
  StampIt-Project/StampIt-Project/Domain/Entities/Errors/RepositoryError.swift
  StampIt-Project/StampIt-Project/Domain/Entities/Member.swift
  StampIt-Project/StampIt-Project/Domain/Repository/AccountManageRepository.swift
  StampIt-Project/StampIt-Project/Domain/Repository/GroupManageRepository.swift
  StampIt-Project/StampIt-Project/Domain/UseCase/GroupManageUseCase.swift
  StampIt-Project/StampIt-Project/Domain/UseCaseImpl/GroupManageUseCaseImpl.swift
  StampIt-Project/StampIt-Project/Presentation/GroupMemberManage/SubViewController/MemberMangerOptionViewController.swift
  StampIt-Project/StampIt-Project/Presentation/GroupMemberManage/SubViewModel/MemberManageOptionViewModel.swift
  StampIt-Project/StampIt-Project/Presentation/GroupMemberManage/ViewController/GroupMemberCardCell.swift
  StampIt-Project/StampIt-Project/Presentation/GroupMemberManage/ViewController/GroupMemberManageViewController.swift
  StampIt-Project/StampIt-Project/Presentation/GroupMemberManage/ViewModel/GroupMemberManageViewModel.swift
Labels: ✨ Feature, 🐯 주형

#81 [Feat] STAMPIT-130 미션 상태별 필터링 기능 추가
  StampIt-Project/StampIt-Project/Domain/Entities/MissionStatus.swift
  StampIt-Project/StampIt-Project/Presentation/Common/Component/FilterCell.swift
  StampIt-Project/StampIt-Project/Presentation/Common/Mapper/MissionMapper.swift
  StampIt-Project/StampIt-Project/Presentation/Home/Common/AssignedMissionCell.swift
  StampIt-Project/StampIt-Project/Presentation/Home/MemberMission/View/MemberMissionView.swift
  StampIt-Project/StampIt-Project/Presentation/Home/Model/HomeItem.swift
  StampIt-Project/StampIt-Project/Presentation/Home/MyMission/Model/MyMissionItem.swift
  StampIt-Project/StampIt-Project/Presentation/Home/MyMission/View/MyMissionView.swift
  StampIt-Project/StampIt-Project/Presentation/Home/MyMission/ViewController/MyMissionViewController.swift
  StampIt-Project/StampIt-Project/Presentation/Home/MyMission/ViewModel/MyMissionViewModel.swift
  StampIt-Project/StampIt-Project/Presentation/Home/View/HomeView.swift
  StampIt-Project/StampIt-Project/Presentation/Home/View/Subviews/GroupDashBoardView.swift
  StampIt-Project/StampIt-Project/Presentation/Home/ViewController/HomeViewController.swift
  StampIt-Project/StampIt-Project/Presentation/Home/ViewModel/HomeViewModel.swift
  StampIt-Project/StampIt-Project/Resource/Extensions/Date+Extension.swift
  StampIt-Project/StampIt-Project/Resource/JsonData/family+category.json
Labels: ✨ Feature, 📱 UI/UX, 🐱 다은, 🐛 Bug

#83 [Fix] STAMPIT-175 사용자 피드백 반영
  StampIt-Project/StampIt-Project/Presentation/Invite/ViewController/ReceiveInviteViewController.swift
Labels: ✨ Feature, 🐯 주형
